- name: Upload files to Neocities
  env:
    NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
  run: |
    # Define paths and file types to exclude
    exclude_paths="./.github/* ./README.md"
    
    # Upload only allowed file types, excluding unwanted paths
    for file in $(find . -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.gif' \)); do
      # Skip excluded paths
      skip=false
      for exclude in $exclude_paths; do
        if [[ "$file" == $exclude ]]; then
          skip=true
          break
        fi
      done

      # Upload files not excluded
      if [ "$skip" = false ]; then
        echo "Uploading $file to Neocities"
        curl -F "file=@$file" "https://neocities.org/api/upload" -H "Authorization: Bearer $NEOCITIES_API_KEY"
      fi
    done
