name: Deploy to Neocities

on:
  push:
    branches:
      - main  # Change to whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up variables and get the list of existing files on Neocities
      - name: Fetch existing files from Neocities
        id: neocities_list
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          curl -s "https://neocities.org/api/list" -H "Authorization: Bearer $NEOCITIES_API_KEY" > neocities_list.json

      # Step 3: Delete files from Neocities that do not exist locally
      - name: Delete old files from Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          # Get a list of files to delete based on the JSON list fetched earlier
          for file in $(jq -r '.files[] | select(.is_directory == false) | .path' neocities_list.json); do
            if [ ! -f "$file" ]; then
              echo "Deleting $file from Neocities"
              curl -X POST -F "filenames[]=$file" "https://neocities.org/api/delete" -H "Authorization: Bearer $NEOCITIES_API_KEY"
            fi
          done

      # Step 4: Upload all files to Neocities
      - name: Upload to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          for file in $(find . -type f -not -path './.git/*' -not -path './.github/*' -not -name 'deploy.yml'); do
            curl -F "file=@$file" "https://neocities.org/api/upload" -H "Authorization: Bearer $NEOCITIES_API_KEY"
          done
