# Workflow file: .github/workflows/deploy.yml
name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Neocities package
      - name: Install Neocities module
        run: npm install neocities

      # Step 4: Deploy with username/password
      - name: Deploy to Neocities
        env:
          NEOCITIES_USERNAME: ${{ secrets.NEOCITIES_USERNAME }}
          NEOCITIES_PASSWORD: ${{ secrets.NEOCITIES_PASSWORD }}
        run: |
          node -e "
          const Neocities = require('neocities');
          const api = new Neocities(process.env.NEOCITIES_USERNAME, process.env.NEOCITIES_PASSWORD);

          // Test user/pass connection
          api.info((resp) => {
              if (resp.result !== 'success') {
                  console.error('Auth Error:', resp.message);
                  process.exit(1);
              } else {
                  console.log('Connected to Neocities successfully.');
              }
          });
          "
