name: Deploy to Neocities

on:
  push:
    branches:
      - main  # Change to the branch you're using for deployment (maybe `main` or `master`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cURL (just in case it's not there)
      run: sudo apt-get install -y curl

    - name: Upload to Neocities
      env:
        NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
      run: |
        # Loop through your website files and upload them
        for file in $(find . -type f -not -path './.git/*' -not -path './.github/*'); do
          curl -F "file=@$file" https://neocities.org/api/upload -H "Authorization: Bearer $NEOCITIES_API_KEY"
        done
